### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by oomiracle** [josedolz/SemiDenseNet#5]
Traceback (most recent call last):
  File "./networkTraining.py", line 83, in <module>
    networkTraining(sys.argv[1:])
  File "./networkTraining.py", line 78, in networkTraining
    startTraining(networkModelName,configIniName)
  File "/data/zhanghang/HyperDenseNet-master/src/HyperDenseNet/startTraining.py", line 141, in startTraining
    applyPadding
  File "/data/zhanghang/HyperDenseNet-master/src/HyperDenseNet/Modules/IO/sampling.py", line 80, in getSamplesSubepoch
    imageType
  File "/data/zhanghang/HyperDenseNet-master/src/HyperDenseNet/Modules/IO/loadData.py", line 88, in load_imagesSinglePatient
    [imageData, paddingValues] = applyPadding(imageData, sampleSizes, receptiveField)
  File "/data/zhanghang/HyperDenseNet-master/src/HyperDenseNet/Modules/IO/ImgOperations/imgOp.py", line 57, in applyPadding
    extra_padding = np.maximum(0, np.asarray(sampleSizes,dtype="int16")-(inputImg_arr+left_padding+right_padding))
ValueError: operands could not be broadcast together with shapes (4,) (3,)

**Comment by oomiracle** [comment]
Has anyone encontered the same error with me?
